# Generated by Django 6.0.4 on 2026-04-22 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_files_done_to_collectiontask'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commessa', models.CharField(max_length=200)),
                ('collection_name', models.CharField(max_length=200)),
                ('report_name', models.CharField(max_length=255)),
                ('mode', models.CharField(choices=[('veloce', 'Veloce'), ('ragionamento', 'Ragionamento')], default='veloce', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'In attesa'), ('processing', 'In elaborazione'), ('ready', 'Pronto'), ('error', 'Errore')], default='pending', max_length=20)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('total_queries', models.IntegerField(default=0)),
                ('done_queries', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('query', models.TextField()),
                ('response', models.TextField(blank=True, default='')),
                ('references', models.JSONField(default=list)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.report')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(fields=('commessa', 'collection_name', 'report_name'), name='unique_report_name_per_collection'),
        ),
    ]
