# Generated by Django 6.0.4 on 2026-04-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_report_reportitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectiontask',
            name='status',
            field=models.CharField(choices=[('pending', 'In attesa'), ('processing', 'In elaborazione'), ('ready', 'Pronto'), ('error', 'Errore'), ('cancelled', 'Annullato')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'In attesa'), ('processing', 'In elaborazione'), ('ready', 'Pronto'), ('error', 'Errore'), ('cancelled', 'Annullato')], default='pending', max_length=20),
        ),
    ]
