# Generated by Django 6.0.4 on 2026-04-21 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_collectiontask'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectiontask',
            name='files_done',
            field=models.IntegerField(default=0),
        ),
    ]
